### PR TITLE
fix: orphaned jobs are reset to 'waiting'

### PR DESCRIPTION
**Pull request by larssn**
This PR seeks to fix the case in horizontal server architectures, where a node is killed off by a load balancer, which in turn makes any jobs that node is running "orphaned".

The PR adds a 15 min limit for jobs. If they have been flagged as running for over 15 min, they are reset to 'waiting'.

It's a pretty simple concept, let me know your thoughts about it. We've been running it in a private branch on our production servers for months. We figure that limiting jobs to 15 mins is better than them potentially becoming orphans.

### CODE REVIEW

**Comment by mirzazeyrek** [comment]
2 objections:

1- It's a long shot but there could be cases when an operation might took longer than 15 minutes especially for heavy crons running only once in a week, or once in a month.

2- Checking in each 5 minutes might not fit for all cases. Could there be a way to dynamically arrange those intervals ? 

In addition to those also enabling-disabling option for this feature can be useful.

**Comment by larssn** [comment]
We've moved to a custom simpler solution based on the `select for update` SQL trick. This PR was mainly meant as a "better than nothing"-fix, as we've had the above scenario happen on numerous occasions.

I'm sure there's a better way of officially supporting this logic. I'll leave the PR open, for some future person to either reject or approve.

**Comment by roborourke** [comment]
@larssn hey, thanks for the PR and sorry there hasn't been any reply. This might be something we can handle in the plugin rather than the runner.

Can you elaborate a bit on the solution using `select for update` at all? I'll close this PR out as I agree with @mirzazeyrek's observations but we could continue this conversation in an issue instead.

**Comment by larssn** [comment]
Yes, lemme just dump the official tldr on it:
`The SELECT FOR UPDATE statement allows you to lock the records in the cursor result set. You are not required to make changes to the records in order to use this statement. The record locks are released when the next commit or rollback statement is issued.`

So the idea is that `x` nodes (all linux) try to get the lock for a given URI, and whatever node gets the lock, can run jobs for the next `y` amount of time. We just use the WP CLI for doing so.

This all assumes you have access to the terminal of your linux installation of choice, because you'll need crontab to run the code.

The solution ended up being less than 70 lines of code total, and we're quite happy with a simple solution like that.

**Pull request closed without merging**
