### PR TITLE
Support sockets for DB_NAME

### LINKED ISSUE #14: Runner is not able to use mysql sockets
When we configure wordpress to connec to the database with mysql socket the runner fails to start. We can reproduce it by adding this line to wp-config.php:

define( 'DB_HOST', 'localhost:/tmp/mysql.sock' );

### PR DESCRIPTION
**Pull request by rmccue**
Fixes #14.

@mitaka Can you check if this works for your setup? :)

### CODE REVIEW

**Comment by mitaka** [comment]
Hello,

I have checked out allow-unix-sockets branch and tried running cavalcade runner. This is the error I experience:

Error: SQLSTATE[#2800]: <<Unknown error>>: 1045 Command not supported
#0 /home/greenpeace/Cavalcade-Runner/lib/Runner.php(140): PDO->prepare('SELECT * FROM w...')
#1 /home/greenpeace/Cavalcade-Runner/lib/Runner.php(80): HM\Cavalcade\Runner\Runner->get_next_job()
#2 /home/greenpeace/Cavalcade-Runner/bin/cavalcade(18): HM\Cavalcade\Runner\Runner->run()
#3 {main}

It looks like the connection to the database is created but cannot execute query. The query in question is:

SELECT * FROM wp_cavalcade_jobs WHERE nextrun < NOW() AND status = \"waiting\"

I do not believe that this is related to the fix you made.

**Comment by rmccue** [comment]
@mitaka Do you happen to be using ProxySQL? Seems like [that doesn't support prepared queries](https://github.com/sysown/proxysql/blob/e5e26b27a2589bbdfbb95217a90106281e4ae4f9/lib/MySQL_Session.cpp#L683-L691).

**Comment by mitaka** [comment]
Yes proxysql is enabled. This explains it.

**Comment by rmccue** [comment]
Great; sounds like if you're getting to that stage, the socket support worked, so let's ship this PR.

**Pull request merged**
