### PR TITLE
Added a global variable to control whether to log to syslog.

### PR DESCRIPTION
**Pull request by larssn**
Our logs are flooded by the runner, time to give people an option to turn it off.

Also added a .gitignore

### CODE REVIEW

**Comment by rmccue** [comment]
Your indentation is off in this patch, note that we use tabs for indentation.

I'm not sure I see the point of this; if you don't want the logs, why can't you just pipe the output to /dev/null?

**Comment by larssn** [comment]
I would argue that most people wouldn't need the logs, as they are extremely verbose (you dump an array in there per worker execution f.ex), hence it would probably be a good idea if they were off by default.

Not sure why the indentations look that way here, they look ok in phpstorm. I'll fix it if you wan't to merge.

Your call :)

**Comment by tillkruss** [comment]
There should be at least log levels to hide verbose info messages but still log errors/warnings.

**Comment by rmccue** [comment]
I'd be happier adding log levels instead, and specifying desired log level via CLI args. We could probably default to Unix-style (silent unless there's an error), and have `--verbose` for the current extended reporting.

**Comment by tillkruss** [comment]
That sounds legit.

**Comment by larssn** [comment]
I'll work on a better version of this then.

**Pull request closed without merging**
